#pragma config(Sensor, in8,    gyroRaw,        sensorGyro)
#pragma config(Sensor, dgtl1,  driveEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           frontRightDrive, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rearRightDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeftDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rearLeftDrive, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "./VRCNERD-nerd_robotc-cfdb3c0a39c3/libGyro/NERD_Gyro.c"//Jason's gyro library.
#include "./VRCNERD-nerd_robotc-cfdb3c0a39c3/libPID/NERD_PID.c" //Jason's PID library courtesy of Jason McKinney.
#include "./Truespeed.h" //Truespeed library courtesy of Jason McKinney.

Gyro gyro;

PID drivePID;
PID gyroPID;
PID gyroDrivePID;

int gyroAngle = 0;
int time = 0;

task monitorGyro();
void driveTarget(int target, int accuracy);
void gyroTurn(int target, int accuracy);
void driveL(int val);
void driveR(int val);
int min(int a, int b);
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

  //initialize the gyro
  gyroInit(gyro, in8); //first is the name of the sensor, second is the port it is plugged in to

  //initialize the values for your PID

  //Parameters: P, I, D, I inner range, I outer range, D inner range, D outer range
  //over loaded so that you don't have to specifiy the D inner and outer ranges
  pidInit (drivePID, 1, 0, 0, 9999, 9999, 9999, 9999);
  pidInit (gyroPID, 1, 0, 0, 9999, 9999, 9999, 9999);
  pidInit (gyroDrivePID, 1, 0, 0, 9999, 9999, 9999, 9999);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
 driveTarget(2000,10); //drive forward 2000 +- 10 encoder ticks
 gyroTurn(90,2);	//turn 90 degrees to the right +- 2 degrees
 driveTarget(-1000,20); //drive backward 1000 +- 20 encoder ticks
 gyroTurn(-45, 5); //turn left 45 degrees to the left +- 5 degrees
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
    UserControlCodePlaceholderForTesting();
  }
}


/*
Driving PID and turning libraries courtesy of Brian Boxell, DCL team 9605A

TrueSpeed mapping courtesy of Jordan Kiesel, BNS/24c

PID and Gyro libraries courtesy of Jason McKinney, QCC2/2625

All of this is designed to work with the Vex EDR system. Motors are given values between -127 and 127. The Truespeed mapping accounts
for the nonlinearity of the motor values so that you get smoother and more accurate accelerations. The gyro library by Jason McKinney is
specifically designed to account for drift in the Vex yaw rate gyroscope. Depending on the quality of your gyro, you may be able to omit
the functions in the monitorGyro task, and just use the raw data of the gyro.

In the implementation of this code, there are a bunch of variables and things defined elsewhere. These include global variables (notably the
gyroAngle float), and the initializations of the PIDs. You must initialize all PIDs at the beginning of your program.4
*/


/*
* uses PID to drive to the desired target, within the specified accuracy
* @param target: integer target value to drive to
* @param accuracy: integer value asssigned to the desired accuracy (drives to target +- this number)
*/
void driveTarget(int target, int accuracy) {
	bool atTarget = false;
	int targetAngle = gyroAngle;
	int repsAtTarget = 0;
	//go into the loop that will repeat to update motor values and break when at target
	while (!atTarget) {
		//calculate the value the motors should be set at based on its position relative to the target
		int val = pidCalculate(drivePID, target, SensorValue[driveEnc]);
		//the left and right drive values should be different in order to correct getting turned as specified by the gyro value
		int leftVal = val + pidCalculate(gyroDrivePID, targetAngle, gyroAngle);
		int rightVal = val - pidCalculate(gyroDrivePID, targetAngle, gyroAngle);
		motor[frontRightDrive] = motor[frontLeftDrive] = ((leftVal) >= 0 ? 1 : -1)*TrueSpeed[min(fabs(leftVal),127)];
		motor[rearRightDrive] = motor[rearLeftDrive] = ((rightVal) >= 0 ? 1 : -1)*TrueSpeed[min(fabs(rightVal),127)];
		//if the sensor value is within the desired range of the target
		if (abs(SensorValue[driveEnc]-target) < accuracy) {
			//if the sensor value is within the range for multiple iterations of the loop where each loop is approximately 20ms
			if (repsAtTarget > 12) {
				//break out of the while loop
				atTarget = true;
			}
			else {
				repsAtTarget++;
			}
		}
		else {
			repsAtTarget = 0;
		}
	}
	//zero the value of the encoder so that the next time this procedure is called, the encoder will be starting at zero again
	SensorValue[driveEnc] = 0;
}


//updates the angle of the robot, makes it so that the angle is always described to be within -180 <= angle <= 180 degrees.
//this task runs in the background, the code could also just be copy and pasted into the main loop of the program and work the same.
task monitorGyro() {
	while (true) {
		//takes the summation of the gyro turning rates over time (the integral of the rate is the position)
		float deltaTime = (nPgmTime - time)/1000.0;
		time = nPgmTime;
		gyroAngle += SensorValue[gyro]*deltaTime;
		wait1Msec(20);
		//makes sure that the gyro angle is always represented between -180 and 180
		if (fabs(gyroAngle)>180) {
			gyroAngle = ((gyroAngle>0)? -1: 1)*(360-fabs(gyroAngle));
		}
		wait1Msec(20);
	}
}


/*
* uses PID to turn to the desired target, within the specified accuracy
* @param target: integer target value to drive to
* @param accuracy: integer value asssigned to the desired accuracy (drives to target +- this number)
*/
void gyroTurn(int target, int accuracy) {
	bool gyroAtTarget = false;
	int repsAtTarget = 0;
	//go into the loop that will repeat to update motor values and break when at target
	while (!gyroAtTarget) {
		// calculate the desired motor value based on the sensor value relative to the target
		float drive = pidCalculate(gyroPID, target, gyroAngle);
		drive = ((fabs(gyroAngle-target)>180)? -1 : 1)*drive;
		driveL(drive);
		driveR(drive);
		//if the sensor value is within the desired range of the target
		if (fabs(gyroAngle-target) < accuracy) {
			//if the sensor value is within the range for multiple iterations of the loop where each loop is approximately 20ms
			if (repsAtTarget > 12) {
				//break out of the loop
				gyroAtTarget = true;
			}
			else {
				repsAtTarget++;
			}
		}
		else {
			repsAtTarget = 0;
		}
	}
	SensorValue[driveEnc] = 0; //zero the value of the drive encoder
}

//called from the gyro turn task, makes sure it is a valid motor input and updates drive motors;
void driveL(int val){
	val = (abs(val) > 127)? 127 * val/abs(val) : val; //ensure val is under 127
	motor[rearLeftDrive] = motor[frontLeftDrive] = ((val) >= 0 ? 1 : -1)*TrueSpeed[min(fabs(val),127)];
}
// same thing as driveL, but with a different negative sign
void driveR(int val){
	val = abs(val) > 127 ? 127 * val/abs(val) : val; //ensure val is under 127
	motor[rearRightDrive] = motor[frontRightDrive] = ((val) >= 0 ? -1 : 1)*TrueSpeed[min(fabs(val),127)];
}

//returns the minimum of 2 parameters, used in the TrueSpeed call
int min(int a, int b){
	if(a>b)
		return b;
	return a;
}
